units:
  length: "mm"
  potential: "V"
  angle: "deg"
  temperature: "K"
name: "P42575A"
medium: "vacuum"
detectors:
  - semiconductor:
      material: "HPGe"
      impurity_density:
        name: "cylindrical"
        r:
          init: 0.0
          gradient: 0.0
        z:
          init: -7.0e6
          gradient: 53000.0
      geometry:
        difference:
          - difference:
              - translate:
                  tube:
                    name: "Initial Cylinder"
                    phi:
                      to: 360.0
                      from: 0.0
                    r:
                      to: 34.7
                      from: 0.0
                    h: 50.84
                  z: 25.42
              - translate:
                  cone:
                    name: "Lower Cone"
                    phi:
                      to: 360.0
                      from: 0.0
                    r:
                      bottom:
                        to: 36.0
                        from: 29.300000000000004
                      top:
                        to: 36.0
                        from: 34.7
                    h: 5.3999999999999995
                  z: 1.8
          - union:
              - tube:
                  r: 1.03
                  h: 1.6320000000000001
                  origin:
                    z: 0.544
              - torus:
                  r_tube: 1.36
                  r_torus: 1.03
      temperature: 90.0
    contacts:
      - material: "HPGe"
        geometry:
          union:
            - tube:
                r: 1.03
                h: 0
                origin:
                  z: 1.36
            - torus:
                theta:
                  to: 90.0
                  from: 0.0
                r_tube:
                  to: 1.36
                  from: 1.36
                r_torus: 1.03
        id: 1
        potential: 0.0
      - material: "HPGe"
        geometry:
          union:
            - translate:
                tube:
                  phi:
                    to: 360.0
                    from: 0.0
                  r:
                    to: 34.7
                    from: 34.7
                  h: 46.34
                z: 27.67
            - translate:
                tube:
                  phi:
                    to: 360.0
                    from: 0.0
                  r:
                    to: 34.7
                    from: 0
                  h: 0.0
                z: 50.84
            - translate:
                cone:
                  phi:
                    to: 360.0
                    from: 0.0
                  r:
                    bottom:
                      to: 30.200000000000003
                      from: 30.200000000000003
                    top:
                      to: 34.7
                      from: 34.7
                  h: 4.5
                z: 2.25
        id: 2
        potential: 2300.0
    # virtual_drift_volumes:
    #   - model: "arbitrary"
    #     id: 4
    #     geometry:
    #       tube:
    #         r: 30.2
    #         h: 0.002
    #         origin:
    #           z: 0.001
grid:
  coordinates: "cylindrical"
  axes:
    phi:
      boundaries: "periodic"
      to: 0
      from: 0
    r:
      boundaries: "inf"
      to: 40.0
    z:
      boundaries:
        left: "inf"
        right: "inf"
      to: 60.0
      from: -10
